name: Gerar 3 Posts Automáticos

on:
  schedule:
    - cron: '0 12 * * *'   # 9h (horário de Brasília)
    - cron: '0 18 * * *'   # 15h BRT
    - cron: '0 0 * * *'    # 21h BRT
  workflow_dispatch:       # permite rodar manualmente pelo GitHub

jobs:
  gerar-post:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🐍 Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 📄 Criar variáveis de ambiente
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: 🤖 Rodar o script de geração
        run: python scripts/gerar_post.py

      - name: 📤 Commit e Push dos novos posts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add content/posts/ public/results/
          git diff --quiet && echo "Nenhuma mudança" || (git commit -m "✨ Novo post automático com imagem gerada por IA" && git push)

      - name: 🚀 Disparar deploy na Vercel
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"